//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDPIAS_STORE
{
    using System;
    using System.Collections.Generic;
    
    public partial class chemical_exchange_department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public chemical_exchange_department()
        {
            this.storage_tracker = new HashSet<storage_tracker>();
        }
    
        public int Id { get; set; }
        public int sender_department_id { get; set; }
        public int sender_head_id { get; set; }
        public int receiver_department_id { get; set; }
        public int receiver_head_id { get; set; }
        public int department_storage_id { get; set; }
        public string quentity { get; set; }
        public byte receiver_acknowledge_status { get; set; }
        public string receiver_response_message { get; set; }
        public System.DateTime request_date { get; set; }
        public System.DateTime sender_head_response_date { get; set; }
        public System.DateTime receiver_head_response_date { get; set; }
        public bool is_collected { get; set; }
        public System.DateTime collected_date { get; set; }
        public byte status { get; set; }
    
        public virtual department_storage department_storage { get; set; }
        public virtual department department { get; set; }
        public virtual department_head department_head { get; set; }
        public virtual department department1 { get; set; }
        public virtual department_head department_head1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<storage_tracker> storage_tracker { get; set; }
    }
}
