//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDPIAS_STORE
{
    using System;
    using System.Collections.Generic;
    
    public partial class chemical
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public chemical()
        {
            this.department_to_store_request = new HashSet<department_to_store_request>();
            this.head_chemical_storage = new HashSet<head_chemical_storage>();
            this.main_chemical_storage = new HashSet<main_chemical_storage>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string cas_number { get; set; }
        public string image_structure { get; set; }
        public string molicular_formula { get; set; }
        public string molicular_weight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<department_to_store_request> department_to_store_request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<head_chemical_storage> head_chemical_storage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<main_chemical_storage> main_chemical_storage { get; set; }
    }
}
