//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDPIAS_STORE
{
    using System;
    using System.Collections.Generic;
    
    public partial class department_head
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public department_head()
        {
            this.chemical_exchange_department = new HashSet<chemical_exchange_department>();
            this.chemical_exchange_department1 = new HashSet<chemical_exchange_department>();
            this.department_to_store_request = new HashSet<department_to_store_request>();
        }
    
        public int Id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string contact_no { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public int department_id { get; set; }
        public bool is_active { get; set; }
        public byte status { get; set; }
        public System.DateTime created_at { get; set; }
        public string profile_pic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chemical_exchange_department> chemical_exchange_department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chemical_exchange_department> chemical_exchange_department1 { get; set; }
        public virtual department department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<department_to_store_request> department_to_store_request { get; set; }
    }
}
