//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDPIAS_STORE
{
    using System;
    using System.Collections.Generic;
    
    public partial class department_to_store_request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public department_to_store_request()
        {
            this.department_storage = new HashSet<department_storage>();
            this.storage_tracker = new HashSet<storage_tracker>();
        }
    
        public int Id { get; set; }
        public int department_id { get; set; }
        public int chemical_id { get; set; }
        public int measurement_unit_id { get; set; }
        public string quentity { get; set; }
        public int department_head_id { get; set; }
        public int store_manager_id { get; set; }
        public byte is_approved_by_sender_head { get; set; }
        public byte is_approved_by_store_manager { get; set; }
        public System.DateTime request_date { get; set; }
        public Nullable<System.DateTime> head_approved_date { get; set; }
        public Nullable<System.DateTime> store_manager_approved_date { get; set; }
        public bool is_collected { get; set; }
        public Nullable<System.DateTime> collected_date { get; set; }
        public string store_manager_response_message { get; set; }
        public byte status { get; set; }
    
        public virtual chemical chemical { get; set; }
        public virtual department department { get; set; }
        public virtual department_head department_head { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<department_storage> department_storage { get; set; }
        public virtual measurement_unit measurement_unit { get; set; }
        public virtual store_manager store_manager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<storage_tracker> storage_tracker { get; set; }
    }
}
