//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDPIAS_STORE
{
    using System;
    using System.Collections.Generic;
    
    public partial class department_storage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public department_storage()
        {
            this.chemical_exchange_department = new HashSet<chemical_exchange_department>();
        }
    
        public int Id { get; set; }
        public int request_id { get; set; }
        public int measurement_unit_id { get; set; }
        public string quentity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chemical_exchange_department> chemical_exchange_department { get; set; }
        public virtual department_to_store_request department_to_store_request { get; set; }
        public virtual measurement_unit measurement_unit { get; set; }
    }
}
