//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDPIAS_STORE
{
    using System;
    using System.Collections.Generic;
    
    public partial class main_chemical_storage
    {
        public int Id { get; set; }
        public int head_id { get; set; }
        public int chemical_id { get; set; }
        public int measurement_unit_id { get; set; }
        public string original_quantity { get; set; }
        public string current_quantity { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime expiry_date { get; set; }
        public System.DateTime manufacture_date { get; set; }
        public string molecular_weight { get; set; }
        public string storage_condition { get; set; }
        public byte hazard_level { get; set; }
        public string supplier_company_name { get; set; }
        public int chemical_type_id { get; set; }
        public int chemical_state_id { get; set; }
        public virtual chemical chemical { get; set; }
        public virtual chemical_state chemical_state { get; set; }
        public virtual chemical_type chemical_type { get; set; }
        public virtual measurement_unit measurement_unit { get; set; }
        public virtual store_manager store_manager { get; set; }
    }
}
