//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDPIAS_STORE
{
    using System;
    using System.Collections.Generic;
    
    public partial class main_glassware_storage
    {
        public int id { get; set; }
        public int head_id { get; set; }
        public int glassware_id { get; set; }
        public int measurement_unit_id { get; set; }
        public string original_quantity { get; set; }
        public string current_quantity { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual glassware glassware { get; set; }
        public virtual measurement_unit measurement_unit { get; set; }
        public virtual store_manager store_manager { get; set; }
    }
}
