//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDPIAS_STORE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_pdpiasEntities1 : DbContext
    {
        public db_pdpiasEntities1()
            : base("name=db_pdpiasEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chemical> chemicals { get; set; }
        public virtual DbSet<chemical_exchange_department> chemical_exchange_department { get; set; }
        public virtual DbSet<chemical_state> chemical_state { get; set; }
        public virtual DbSet<chemical_type> chemical_type { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<department_head> department_head { get; set; }
        public virtual DbSet<department_storage> department_storage { get; set; }
        public virtual DbSet<department_to_store_request> department_to_store_request { get; set; }
        public virtual DbSet<glassware> glasswares { get; set; }
        public virtual DbSet<head_chemical_storage> head_chemical_storage { get; set; }
        public virtual DbSet<lab_technician> lab_technician { get; set; }
        public virtual DbSet<main_chemical_storage> main_chemical_storage { get; set; }
        public virtual DbSet<main_glassware_storage> main_glassware_storage { get; set; }
        public virtual DbSet<measurement_unit> measurement_unit { get; set; }
        public virtual DbSet<principal> principals { get; set; }
        public virtual DbSet<storage_tracker> storage_tracker { get; set; }
        public virtual DbSet<store_manager> store_manager { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
