//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDPIAS_STORE
{
    using System;
    using System.Collections.Generic;
    
    public partial class principal
    {
        public int Id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string contact_no { get; set; }
        public string email { get; set; }
        public System.DateTime registered_at { get; set; }
        public bool is_active { get; set; }
        public string profile_pic { get; set; }
        public string password { get; set; }
    }
}
