//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDPIAS_STORE
{
    using System;
    using System.Collections.Generic;
    
    public partial class storage_tracker
    {
        public int Id { get; set; }
        public Nullable<bool> is_department_to_department { get; set; }
        public Nullable<bool> is_department_to_storage { get; set; }
        public Nullable<int> department_to_department_id { get; set; }
        public Nullable<int> department_to_storage_id { get; set; }
    
        public virtual chemical_exchange_department chemical_exchange_department { get; set; }
        public virtual department_to_store_request department_to_store_request { get; set; }
    }
}
